// Product Catalog Data
// DO NOT EDIT THIS FILE - Use it in catalog.js

const products = [
  {
    id: 1,
    name: "Gaming Mouse",
    price: 29.99,
    category: "electronics",
    image: "🖱️",
    stock: 15,
    description: "High-precision gaming mouse with RGB lighting"
  },
  {
    id: 2,
    name: "Coffee Mug",
    price: 12.99,
    category: "home",
    image: "☕",
    stock: 50,
    description: "Ceramic mug, dishwasher safe"
  },
  {
    id: 3,
    name: "Notebook",
    price: 5.99,
    category: "office",
    image: "📓",
    stock: 100,
    description: "Spiral-bound, 100 pages"
  },
  {
    id: 4,
    name: "Headphones",
    price: 79.99,
    category: "electronics",
    image: "🎧",
    stock: 8,
    description: "Wireless noise-cancelling headphones"
  },
  {
    id: 5,
    name: "T-Shirt",
    price: 19.99,
    category: "clothing",
    image: "👕",
    stock: 30,
    description: "Cotton t-shirt, various sizes"
  },
  {
    id: 6,
    name: "Desk Lamp",
    price: 34.99,
    category: "home",
    image: "💡",
    stock: 20,
    description: "LED desk lamp with adjustable brightness"
  },
  {
    id: 7,
    name: "Backpack",
    price: 49.99,
    category: "clothing",
    image: "🎒",
    stock: 15,
    description: "Durable backpack with laptop compartment"
  },
  {
    id: 8,
    name: "Keyboard",
    price: 89.99,
    category: "electronics",
    image: "⌨️",
    stock: 12,
    description: "Mechanical keyboard with RGB lighting"
  },
  {
    id: 9,
    name: "Plant Pot",
    price: 14.99,
    category: "home",
    image: "🪴",
    stock: 40,
    description: "Ceramic plant pot with drainage"
  },
  {
    id: 10,
    name: "Pen Set",
    price: 8.99,
    category: "office",
    image: "🖊️",
    stock: 60,
    description: "Set of 5 ballpoint pens"
  },
  {
    id: 11,
    name: "Sneakers",
    price: 69.99,
    category: "clothing",
    image: "👟",
    stock: 18,
    description: "Comfortable running sneakers"
  },
  {
    id: 12,
    name: "Desk Organizer",
    price: 16.99,
    category: "office",
    image: "📎",
    stock: 25,
    description: "Multi-compartment desk organizer"
  }
];
